import { StyleSheet } from 'react-native';
import { palette } from './colors';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.navy,
  },
  container: {
    flex: 1,
    backgroundColor: palette.slate,
  },
  scrollContainer: {
    paddingBottom: 48,
  },
  header: {
    backgroundColor: palette.navy,
    paddingHorizontal: 20,
    paddingTop: 36,
    paddingBottom: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    elevation: 3,
    shadowColor: palette.black,
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  headerInfo: {
    flexShrink: 1,
  },
  headerTitle: {
    color: palette.white,
    fontSize: 22,
    fontWeight: '700',
  },
  headerSubtitle: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    marginTop: 6,
    lineHeight: 18,
  },
  headerBadge: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  headerBadgeText: {
    color: palette.white,
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0.4,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    gap: 10,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(15, 118, 110, 0.15)',
  },
  chipActive: {
    backgroundColor: palette.white,
  },
  chipText: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
  },
  chipTextActive: {
    color: palette.navy,
    fontWeight: '600',
  },
  balanceRow: {
    flexDirection: 'row',
    gap: 16,
    paddingHorizontal: 20,
    marginTop: -40,
  },
  balanceCard: {
    flex: 1,
    borderRadius: 20,
    padding: 20,
    backgroundColor: palette.white,
    elevation: 3,
    shadowColor: palette.black,
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  balanceCardContent: {
    gap: 18,
  },
  balanceLabel: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 14,
    fontWeight: '500',
  },
  balanceAmount: {
    color: palette.white,
    fontSize: 24,
    fontWeight: '700',
  },
  balanceSubtext: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 12,
  },
  balanceAction: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  balanceActionText: {
    color: palette.white,
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.4,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    paddingHorizontal: 20,
    marginTop: 28,
  },
  actionButton: {
    flexBasis: '48%',
    padding: 18,
    borderRadius: 18,
    backgroundColor: palette.white,
    elevation: 2,
    shadowColor: palette.black,
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  actionButtonLabel: {
    color: palette.white,
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  section: {
    paddingHorizontal: 20,
    marginTop: 32,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    color: palette.black,
    fontSize: 18,
    fontWeight: '700',
  },
  sectionHint: {
    color: palette.aqua,
    fontSize: 12,
    marginTop: 4,
  },
  sectionActionButton: {
    backgroundColor: palette.emerald,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  sectionActionText: {
    color: palette.white,
    fontSize: 13,
    fontWeight: '600',
  },
  emptyState: {
    backgroundColor: palette.white,
    padding: 24,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: palette.black,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: palette.black,
    marginBottom: 8,
  },
  emptyDescription: {
    fontSize: 13,
    color: palette.gray,
    textAlign: 'center',
    lineHeight: 18,
  },
  categoryCard: {
    backgroundColor: palette.white,
    padding: 20,
    borderRadius: 20,
    marginBottom: 16,
    elevation: 2,
    shadowColor: palette.black,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  categoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  categoryName: {
    fontSize: 16,
    fontWeight: '600',
    color: palette.black,
  },
  categoryActions: {
    flexDirection: 'row',
    gap: 8,
  },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.slate,
  },
  iconButtonText: {
    fontSize: 16,
  },
  categoryStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  categoryStatLabel: {
    color: palette.gray,
    fontSize: 12,
  },
  categoryStatValue: {
    color: palette.black,
    fontSize: 15,
    fontWeight: '600',
  },
  progressBar: {
    height: 10,
    borderRadius: 8,
    backgroundColor: palette.graySoft,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    backgroundColor: palette.aqua,
  },
  progressOverflow: {
    backgroundColor: palette.danger,
  },
  progressFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressText: {
    color: palette.gray,
    fontSize: 12,
  },
  remainingText: {
    color: palette.emerald,
    fontSize: 13,
    fontWeight: '600',
  },
  clickHint: {
    color: palette.gray,
    fontSize: 11,
    marginTop: 12,
    textAlign: 'center',
  },
  transactionItem: {
    backgroundColor: palette.white,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    borderRadius: 18,
    marginBottom: 12,
    shadowColor: palette.black,
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  transactionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    backgroundColor: palette.slate,
  },
  transactionDetails: {
    flex: 1,
  },
  transactionTitle: {
    fontSize: 15,
    color: palette.black,
    fontWeight: '600',
  },
  transactionMeta: {
    fontSize: 12,
    color: palette.gray,
    marginTop: 2,
  },
  transactionAmount: {
    fontSize: 16,
    fontWeight: '700',
  },
  amountDeposit: {
    color: palette.purple,
  },
  amountIncome: {
    color: palette.emerald,
  },
  amountExpense: {
    color: palette.danger,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17,24,39,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: palette.white,
    width: '100%',
    borderRadius: 24,
    padding: 24,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.black,
  },
  modalSubtitle: {
    fontSize: 13,
    color: palette.gray,
    marginBottom: 16,
    lineHeight: 18,
  },
  modalClose: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: palette.slate,
  },
  modalCloseText: {
    fontSize: 18,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: palette.black,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: palette.grayLight,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: palette.black,
    marginBottom: 16,
    backgroundColor: palette.white,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 12,
  },
  inputSmall: {
    flex: 1,
  },
  helper: {
    fontSize: 12,
    color: palette.gray,
    marginBottom: 16,
  },
  chipSelector: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 18,
  },
  colorSwatch: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorSwatchActive: {
    borderColor: palette.black,
  },
  categoryPicker: {
    maxHeight: 220,
    borderWidth: 1,
    borderColor: palette.grayLight,
    borderRadius: 18,
    padding: 12,
    marginBottom: 18,
  },
  categoryOption: {
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: palette.slate,
    marginBottom: 10,
  },
  categoryOptionActive: {
    borderColor: palette.aqua,
    backgroundColor: '#E0F2FE',
  },
  categoryOptionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: palette.black,
  },
  categoryOptionMeta: {
    fontSize: 12,
    color: palette.gray,
    marginTop: 4,
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 8,
  },
  secondaryButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: palette.slate,
  },
  secondaryButtonText: {
    color: palette.black,
    fontWeight: '600',
    fontSize: 14,
  },
  primaryButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: palette.navyLight,
  },
  primaryButtonAccent: {
    backgroundColor: palette.emerald,
  },
  primaryButtonText: {
    color: palette.white,
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 0.4,
  },
  dangerButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: palette.danger,
  },
  dangerButtonText: {
    color: palette.white,
    fontSize: 14,
    fontWeight: '700',
  },
  detailsBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  pill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: palette.slate,
  },
  pillText: {
    fontSize: 12,
    color: palette.gray,
  },
  detailBlock: {
    backgroundColor: palette.slate,
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  detailBlockTitle: {
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 6,
    color: palette.black,
  },
  divider: {
    height: 1,
    backgroundColor: palette.grayLight,
    marginVertical: 18,
  },
  loader: {
    marginTop: 48,
  },
  banner: {
    backgroundColor: '#DCFCE7',
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginHorizontal: 20,
    marginTop: 24,
  },
  bannerText: {
    flex: 1,
    fontSize: 14,
    color: palette.teal,
  },
});
